################################################################################
###
### Replication of Gartzke 2007, "The Capitalist Peace," replacing CINC ratios
### with DOE scores
###
### Replicating Table 1, Model 4
###
################################################################################

library("caret")
library("dplyr")
library("foreign")

raw_gartzke_2007 <- read.dta("gartzke-2007.dta")
doe_dyad <- read.csv("../R/results-predict-dyad.csv")

## Rename spline variables generated by Stata
##
## R dislikes variable names starting with underscores
data_gartzke_2007 <- raw_gartzke_2007
names(data_gartzke_2007) <- gsub("^\\_",
                                 "T.",
                                 names(data_gartzke_2007))

## Convert response to factor
data_gartzke_2007 <- data_gartzke_2007 %>%
    mutate(maoznewl = factor(
               maoznewl,
               levels = 0:1,
               labels = c("No", "Yes")
           ))

## Merge in DOE scores
##
## Using undirected since the sample is undirected dyads -- also need to compute
## max and min for consistency, since the A/B labels are exchangeable
data_gartzke_2007 <- left_join(data_gartzke_2007,
                               doe_dyad,
                               by = c(statea = "ccode_a",
                                      stateb = "ccode_b",
                                      year = "year")) %>%
    mutate(VictoryMax = pmax(VictoryA, VictoryB),
           VictoryMin = pmin(VictoryA, VictoryB))
stopifnot(with(data_gartzke_2007, sum(is.na(VictoryA)) == 0))

## Replicate original model and cross-validate
set.seed(707)
f_gartzke_2007 <-
    maoznewl ~ demlo + demhi + deplo + capopenl + rgdppclo + gdpcontg + contig +
        logdstab + majpdyds + alliesr + lncaprt + namerica + samerica + europe +
        africa + nafmeast + asia + T.spline1 + T.spline2 + T.spline3
cr_gartzke_2007 <- train(
    form = f_gartzke_2007,
    data = data_gartzke_2007,
    method = "glm",
    metric = "logLoss",
    trControl = trainControl(
        method = "repeatedcv",
        number = 10,
        repeats = 10,
        returnData = FALSE,
        summaryFunction = mnLogLoss,
        classProbs = TRUE,
        trim = TRUE
    )
)

## Don't save cross-validation indices (takes tons of space with large N)
cr_gartzke_2007$control$index <- NULL
cr_gartzke_2007$control$indexOut <- NULL

prettyNum(coef(cr_gartzke_2007$finalModel))

## Replace (logged) capability ratio with (logged) DOE scores and run again
set.seed(77077)
doe_gartzke_2007 <- train(
    form = update(f_gartzke_2007,
                  . ~ . - lncaprt + log(VictoryMax) + log(VictoryMin)),
    data = data_gartzke_2007,
    method = "glm",
    metric = "logLoss",
    trControl = trainControl(
        method = "repeatedcv",
        number = 10,
        repeats = 10,
        returnData = FALSE,
        summaryFunction = mnLogLoss,
        classProbs = TRUE,
        trim = TRUE
    )
)

## Don't save cross-validation indices (takes tons of space with large N)
doe_gartzke_2007$control$index <- NULL
doe_gartzke_2007$control$indexOut <- NULL

prettyNum(coef(doe_gartzke_2007$finalModel))

save(data_gartzke_2007,
     cr_gartzke_2007,
     doe_gartzke_2007,
     file = "results-gartzke-2007.rda")
